### ISSUE TITLE
TOKEN REFRESH FAILED

### ISSUE THREAD

**Issue by Tiemichael** [methylDragon/onemapsg-api-client#1]
Hi,
thank you for this nice library, it's really helpful.
It seems that the API for authentication was changed from V1.02 to V1.03 - so it's no longer possible to get a token.
Now instead of  ' - multipart/form-data' , it expects '- application/json'

Maybe you can have a look and possibly fix it!
Thanks!

**Comment by danweecc** [comment]
You can fix this by editing onemap_client.py in the get_token function, by doing:-

jsondata = {"email":email, "password":password}
response = requests.post(self.url_base + "/privateapi/auth/post/getToken",
        json=jsondata, headers={"Content-Type":"application/json"})

**Comment by methylDragon** [comment]
Nice fix, do could you write a PR for it? :O

**Comment by methylDragon** [comment]
This should be fixed with https://github.com/methylDragon/onemapsg-api-client/commit/1ebfbabb43f8ed941d617fd16f081c904d49d654

Remember to reinstall the package!!

`pip install --upgrade --force-reinstall onemapsg`
